### ISSUE TITLE
Times on play button / in outpost not matching audio file length

### ISSUE THREAD

**Issue by vsinghkpcc** [SCPR/SCPRv4#1124]
ISSUE: The time listed in outpost / on the "preview" play button is shorter than the original file length (which is represented correctly in the player)

EXAMPLE:
<img width="1419" alt="screen shot 2018-02-15 at 9 03 49 am" src="https://user-images.githubusercontent.com/13337277/36263239-65ee4c02-122f-11e8-93c3-5bf1d030b2b1.png">

**Comment by vsinghkpcc** [comment]
Another example, which should be ~54 min is displaying as ~8 min: https://www.scpr.org/programs/the-frame/2018/02/19/17874/

**Comment by Ravenstine** [comment]
After having done some investigation, this seems to be the best explanation:
https://github.com/moumar/ruby-mp3info/issues/42

Granted, I couldn't directly replicate the problem; identical mp3 files uploaded in the by the same means returns the correct duration.  When I re-run #compute_duration on the problem audio in production, it generates the correct duration, which is why you see it now displaying correctly on this episode:
http://www.scpr.org/programs/take-two/2018/02/14/17852

There's no evidence that the file was swapped somehow.

Our version of ruby-mp3info is older than that issue referenced above, so it's currently the best explanation.  I've updated the gem and we'll see if the issue goes away.

https://github.com/SCPR/SCPRv4/commit/fda765c1b8842299c5fca1dd12da4ef0dedb6db9
