### ISSUE TITLE
Investigate Ads on Web Live Stream

### ISSUE THREAD

**Issue by vsinghkpcc** [SCPR/SCPRv4#1197]
AC
- [x] Determine why ads intermittently do not play the audio / display the companion ad on web live stream

**Comment by nakedsushi** [comment]
My first guess is that the ads that don't play are http, so CORS error.

**Comment by nakedsushi** [comment]
<img width="1044" alt="screen shot 2018-05-31 at 8 05 59 am" src="https://user-images.githubusercontent.com/360040/40790449-d0d51452-64a9-11e8-9107-b367ca90b025.png">

Google Tag Manager is loading ads through HTTP, not HTTPs. The app code is already requesting GTM through the HTTPs, so there's not much I can do here. @patrickdougall do you have any thoughts about this?

**Comment by patrickdougall** [comment]
The two issues here are Salesforce Marketing Cloud analytics (collect.igodigital.com) and Nielsen (secure-drm.imrworldwide.com). I disabled the Marketing Cloud script in GTM, and I was served an ad on livestream. The Nielsen script is hard-coded, I believe, and not through GTM.

May be worth testing a bit before closing out, but I got High Tech termite voice and banner on livestream several times after the change.

**Comment by nakedsushi** [comment]
Thanks @patrickdougall I pushed a fix to request https of the Nielson script, so that should be working now.  The other issue is that adtechus.com sometimes gives an error response, so we end up not loading the ad.  Gonna close this as fixed for now and open a new ticket to investigate adtechus.com (https://adserver.adtechus.com/?adrawdata/3.0/5511.1/3590535/0/0/header=yes;adct=text/xml;cors=yes) later.

**Comment by nakedsushi** [comment]
https://github.com/SCPR/SCPRv4/issues/1214
