### ISSUE TITLE
The Big One: Episode List Component performs GET request to populate data

### ISSUE THREAD

**Issue by arellaTV** [SCPR/SCPRv4#1321]
AC:

~~- [ ] There is a get request to the Megaphone API that returns an episode list array~~
- [x] The title, description, and embed code are automatically populated in the scaffold 

Megaphone API documentation: https://developers.megaphone.fm/

**Comment by jo-im** [comment]
Instead of getting data from the Megaphone API, Jay and I have decided to use the XML feed because Megaphone API doesn't offer a public key that only allows GET requests.

AC: 
- [ ] There is a request to the XML feed that provides a document containing the episode's title, description, and embed code.
