### ISSUE TITLE
External Programs needs a concept to indicate when audio is no longer available for an episode  

### ISSUE THREAD

**Issue by sdillingham** [SCPR/SCPRv4#241]
Currently, our `sync_external_programs` job fetches new 3rd party program content, saves new objects to the database, and then never touches those objects again. While this works fine for programs who never take down their archived audio, few podcasts (primarily CarTalk and This American Life) take podcast episodes down after 1-2 weeks, resulting in external program episodes in our database which point to audio files that no longer exist.

We need a way to regularly check External Segments and External Episodes and flag them when the file specified in the `audio` path no longer exists. This would also need to be added to the API somehow. It could be a filter param, or we could decide that external content with orphaned audio shouldn't be returned in the API (or on the website) at all since the value of that content to users is practically nil.

**Comment by ewr** [comment]
I suspect that we actually may want expiration rules on the ExternalProgram object, rather than a system to poll the audio objects. I could see that getting really unwieldy, since there are 30k+ objects between ExternalEpisode and ExternalSegment.

This might be something like an `expire_after` field on the ExternalProgram object, and then a scheduler task to expire / delete child objects older than that time.

**Comment by Ravenstine** [comment]
Is the rate at which some shows remove their episodes consistent?  If that's the case, we could have rules set on what episodes to display/delete on a per-show basis(in case some shows have different expiration schedules).

**Comment by ewr** [comment]
Yeah, I would suspect they'll all be different. We'll want to add something that works per-program, and then we'll need to go through the programs we pull in and try to figure out what they support.

**Comment by Ravenstine** [comment]
I've written a Resque job to sweep up expired external episodes and making sure they don't show up in the programs#show even if they haven't been deleted yet.

Is it safe to assume that we would want these episodes to be deleted in daily increments or do we want finer control than that?  Right now, I've given external_programs a column 'days_to_expiry' so that we can know when (external_episodes.created_at + external_programs.days_to_expiry) an episode should be removed.

**Comment by ewr** [comment]
Push a branch up and start a pull request so that we can take a look via the code. 

I would think daily is fine, and I don't know that we would really need them marked expired any sooner than that. We'll just need to be conservative in what we set the expiration value to be, so that for any given show, we've stopped referring to the content by the time they quit serving the audio.

**Comment by ewr** [comment]
Closed via #264.
