### ISSUE TITLE
API: Programs#index endpoint is too slow

### ISSUE THREAD

**Issue by ewr** [SCPR/SCPRv4#252]
For no good reason, the `programs#index` API endpoint averages ~250ms for response times.

https://rpm.newrelic.com/accounts/71496/applications/446356/transactions#id=5b22436f6e74726f6c6c65722f6170692f7075626c69632f76332f70726f6772616d732f696e646578222c22225d

It gets hit fairly regularly by the iPhone and Android apps, so it would be worth speeding it up (especially given that it's basically static information).

**Comment by Ravenstine** [comment]
It seems like the related links for each program are causing the most slowdown, which I've yet to find a good solution to; even executing a query to retrieve both the podcast URL and rss URL at once does not noticeably improve performance.  Unfortunately, it seems that these links are used throughout the v4 API.  While the results bulk query to get all the links for a program stored in a variable might make sense for getting 5+ related links, it doesn't seem to make much of a dent in the programs#index endpoint which only gets the two podcast and rss links.

Maybe the related links to a program need to be retrieved through their own query vs including them with the program info returned from the API?  That way if related links aren't often used they can still be retrieved by those who use them without slowing down the index endpoint. 

Some minor slowdown I've noticed is being caused by the fact that #to_program in KpccProgram and ExternalProgram query for episodes and segments, despite neither of those being displayed in the index endpoint.

Are there any reasons why we couldn't implement caching on the response?

**Comment by ewr** [comment]
There's a lot that I don't like about concepts such as `to_program`... 

I'm headed out now, but grab me on Slack tomorrow and walk me through what you've tried. Caching is always an option (and is harmless here), but it tends to mask things underneath that should just be better.

**Comment by ewr** [comment]
![screen shot 2015-05-14 at 2 45 53 pm](https://cloud.githubusercontent.com/assets/204350/7639165/ff7f9b80-fa47-11e4-8eac-c41a8f73f743.png)
