### ISSUE TITLE
Audio Player events need better metadata and more status

### ISSUE THREAD

**Issue by ewr** [SCPR/SCPRv4#254]
Currently, we trigger "Play", "Pause" and "Load" events for audio objects that appear in-page:

https://github.com/SCPR/SCPRv4/blob/6c5434b6a0ed54ee9dbdd44d39d5fc3de4247023/app/views/shared/audio/_new_inpage_audio_player.html.erb#L9-L10

The events need more information in order to be actionable:

* We need the URL of the audio content being played. Currently we just get the page the audio was played on.
* We need an event that fires on audio completion.
* It would be nice to get some sort of a duration event that we could use to understand how long people listen for. Maybe an event that fires for each listened minute, or something like that.

We may want to look into GA's support for video, since they may have some extra features if we pretend our content is videos rather than just logging events.

**Comment by ewr** [comment]
Also... addressing this will probably mean taking the event tracking out of the HTML and putting it into the audio player javascript, which is here:

https://github.com/SCPR/SCPRv4/blob/master/app/assets/javascripts/audio.js.coffee

**Comment by sdillingham** [comment]
Also note that we recently updated SCPRv4 to use GA's Universal Analytics, so if we continue to track these via standard events we'll need to use the new UA methods for pushing events to GA:

https://developers.google.com/analytics/devguides/collection/analyticsjs/events

**Comment by Ravenstine** [comment]
The possibility of determining a "stop" based on page navigation or tab/app switch is not quite as straight forward as I thought when it comes to mobile devices.  For desktop browsers, it's as simple as using the onbeforeunload event on the window, so that some code can be fired off before the tab/window closes.  Apple has omitted this and similar events from their mobile browser.  The only way around this seems to be though listening to link clicks on the page, though this wouldn't account for the user closing the tab or going to a new site.  I suspect this situation is the same on Android(since Apple probably removed that event to prevent code that would block the mobile browser from closing).

Here are the options that I know of for how we can determine a 'stop' depending on what platform:

#### Desktop
Use the 'onbeforeunload' event and also use 'onblur' if the player is no longer playing and has not reached its 'complete' state.

#### Mobile
Use 'onblur' or possibly 'document.hidden' if the player is no longer playing and is not complete.  Links on the episode page that redirect the user elsewhere can also trigger a stop.  We would not know if a user decides to close the tab/window or navigate using their own URL.


That is if we even still want to do something like this.

**Comment by ewr** [comment]
Yeah, I'm not sure how much we really care about this if we're going to have to jump through hoops to get it. 

With a Play event and then the quartile / completed events, we'll have a way of loosely figuring out how many people listen for how long, and I think that's sufficient. 

It's also way more than we have now, so I think incrementally improving this is a bigger win than spending too much time on what we think we want right now.

**Comment by sdillingham** [comment]
@Ravenstine This was addressed and deployed as part of this commit, correct?

https://github.com/SCPR/SCPRv4/commit/c6620d6189047dfa5106adb195a80c32fa21b096

I think you can close this issue.

**Comment by ewr** [comment]
There does seem to be an issue with the complete event. Starts and quartiles look correct, but there are barely any complete events.

ER




On Mon, Jun 8, 2015 at 2:41 PM -0700, "Sean Dillingham" <notifications@github.com<mailto:notifications@github.com>> wrote:


@Ravenstine<https://github.com/Ravenstine> This was addressed and deployed as part of this commit, correct?

c6620d6<https://github.com/SCPR/SCPRv4/commit/c6620d6189047dfa5106adb195a80c32fa21b096>

I think you can close this issue.

-

**Comment by Ravenstine** [comment]
The 'complete' event seems to be coming in regularly now.  I will close this and re-open it if we find out otherwise.  I'm pretty confident that the issue has been resolved.
