### ISSUE TITLE
Include DocumentCloud links as embedly items in Outpost

### ISSUE THREAD

**Issue by ezass** [SCPR/SCPRv4#256]
DocumentClound now supports Oembed: 

https://blog.documentcloud.org/blog/2015/05/easier-publishing-with-wordpress-and-oembed/

**Comment by Ravenstine** [comment]
I've added DocumentCloud support in Embeditor.
https://github.com/SCPR/embeditor-rails/pull/4

This example following markup will embed a document in a news story:

```html
<a class="embed-placeholder" data-placement="replace" data-service="documentcloud" href="https://www.documentcloud.org/documents/2095495-use-of-force-report-for-aug-2014-ezell-ford.html">Document</a>
```

How do we want users of Outpost to be able to create this embed code?  I might be wondering this because I am lacking some existing knowledge of how other Oembed codes that are being used(like Embedly) are being generated.

**Comment by sdillingham** [comment]
There's a button on the CKEditor toolbar in Outpost that gives producers an interface to create these placeholder links:

![screen shot 2015-06-25 at 9 15 39 am](https://cloud.githubusercontent.com/assets/442483/8359381/c73ec720-1b1a-11e5-967d-112233c13527.png)

**Comment by sdillingham** [comment]
I believe this is the relevant code:

https://github.com/SCPR/SCPRv4/blob/00555900e1fda9930c7c6b38d0e15ca2e20f8048/public/static/ckeditor/plugins/embed-placeholder/plugin.js
