### ISSUE TITLE
Non-UTF8 character in filename causes file uploads to fail

### ISSUE THREAD

**Issue by ewr** [SCPR/SCPRv4#263]
After the Rails 4.2 upgrade, if an audio file is uploaded with a funky filename, it will raise an exception.

The actual failing code is in `action_dispatch/http/upload.rb:31`:

```ruby
    @original_filename &&= @original_filename.encode "UTF-8"
```

We either need this to be fixed in Rails, or we need to clean the filename before it gets to this point.

**Comment by Ravenstine** [comment]
Is it Encoding::UndefinedConversionError?  I'd think that Rack-utf8_sanitizer would take care of that, but maybe it doesn't force encoding by removing invalid bytes.

**Comment by ewr** [comment]
Here’s a New Relic error report:

https://rpm.newrelic.com/accounts/71496/applications/446356/traced_errors/3355555435

Feel free to investigate. :)

From: Ravenstine
Reply-To: SCPR/SCPRv4
Date: Friday, May 8, 2015 at 12:08 PM
To: SCPR/SCPRv4
Cc: Eric Richardson
Subject: Re: [SCPRv4] Non-UTF8 character in filename causes file uploads to fail (#263)


Is it Encoding::UndefinedConversionError? I'd think that Rack-utf8_sanitizer would take care of that, but maybe it doesn't force encoding by removing invalid bytes.

**Comment by Ravenstine** [comment]
I haven't found any existing solution that does what we need.  I've also tried utf8-cleaner.  My guess is that if any of these utf8 sanitizing gems work, they aren't going deep into the response object; since our file upload is nested inside of form params, they may not even find the file name.

I hacked up this Rack middleware that finds nested hash keys called "filename" and removes invalid byte characters from their string values.  I'm not sure if this how we'd want to go about it, but it's my only proof of concept for how we could fix file names without monkeypatching ActionDispatch.

```ruby
class Sanitizer
  def initialize app
    @app = app
  end
  def call env
    env["rack.request.form_hash"] = sanitize(env["rack.request.form_hash"])
    @app.call env
  end
  def sanitize input
    if input.respond_to? :each_key
      input.each_pair do |k, v|
        input[k] = sanitize_pair k, v
      end
    end
    input
  end
  private
  def sanitize_pair key, value
    if key.to_s.match(/file[_\s]*name/i) && value.is_a?(String)
      value.encode "UTF-8", invalid: :replace, undef: :replace, replace: "_"
    elsif value.is_a? Hash
      sanitize value
    else
      value
    end
  end
end
```
