### ISSUE TITLE
inline asset support: Design technical flow

### ISSUE THREAD

**Issue by vsinghkpcc** [SCPR/SCPRv4#314]
# Proposed Producer Creation Flow: 

1. Producer places their cursor into the body of an article in Outpost where they want to insert an asset.
2. Producer clicks on the Asset icon in the WYSIWYG toolbar.
3. An AssetHost popup chooser window launches and allows the producer to select an asset.
4. Producer finds and selects the appropriate assets, then clicks "Save and Close."
5. Asset placeholder is inserted inline into article body.
6. On save, mark any assets inserted into the body as "inline" so that they are not used for other purposes(like emphasized or slideshow).

# Proposed Client-Side Delivery Flow: 

1. When an article is rendered on SCPRv4, parse the article body to look for any instances of asset placeholders
2. When an asset placeholder is found, extract the asset ID (and localized caption if one exists)  and make a call to the AssetHost API.
3. AssetHost returns a JSON response with Asset URL, Caption, and Credit.
4. SCPRv4 replaces the asset placeholder with a templated HTML fragment that renders the image tag, caption (privileging localized captions), and credit wrapped in the appropriate markup.  

# Proposed Approache for Inline Asset Placeholders

## img tag
`<img class="inline-asset" data-asset-id="12345" />`

# Possible Additional Features:

* Allowing producers to set a positioning attribute on the inline asset (e.g. "float right" or "block")

**Comment by ewr** [comment]
There are several different pieces wrapped up in this:

1. How you select what assets should be attached to the content, and give them captions
2. How you place assets into the body of the content
3. How those assets are represented in the stored raw content
4. How those assets are rendered into the output
5. How those assets are displayed

(1) is functionally already covered by the existing asset chooser. It provides an interface for selecting the assets that should be associated with the story, and communicating that information (with customized captions) back to the content editor. Those assets are then turned into ContentAsset objects attached to the story.

Currently, those assets are then assumed by SCPRv4 to all be intended for the top of the story (if a slideshow is selected, otherwise additional assets are ignored), but that's just the current implementation.

(2) is the first real piece of work. Once assets have been selected for the story, how do you place the ones that you would like to have inline? The placement of the asset view and the body editor isn't ideal for a drag-and-drop situation, but that's how I tackled the same issue for my own purposes (the chosen assets show up in a sidebar next to the editor, making it easy to drag them inline). You could also do the toolbar icon, popup chooser approach, but choosing from the assets attached to the story, not from AssetHost.

Potentially, placing the asset inline would set a flag on the ContentAsset to make it ineligible for use up top. 

For (3), I really dislike HTML in our raw content, but I suspect the ship has already sailed on that. The important thing here would be to not let users think this is just a tag that they can do normal html img tag things with. You want to store the asset id, and potentially any customized display information you need (the equivalent of the asset scheme for the top asset).

(4) should just run through the normal asset rendering pipeline. I can't remember if we run body content through any processing pipelines right now, but adding one that identified assets and replaced them with the appropriate scheme template isn't a hard task.

For (5), it's really just the same question as any other asset on how you want to handle big images vs small ones, landscape vs vertical, etc. Those are just template questions.

**Comment by sdillingham** [comment]
I'm generally supportive of an approach that uses the current Asset Chooser to manage all assets on a story (both inline and lead assets). There are UX drawbacks we need to mitigate as part of an approach that relies on the current Asset Chooser:

* The disconnect between building a set of assets in one place and then using them in another. We can bridge the physical gap by bringing the asset management UI right up below the body field in Outpost, but there's also a conceptual disconnect that we need to mitigate. Popping up the Asset Chooser, selecting one or more photos, and then having to close the popup and click into the body field to place the asset(s) you've chosen - that feels like a content creation flow that's optimized for cleanly modeling content at the expense of a more elegant authoring experience.
* Within the display of thumbnails of assets currently on a story, we need UI that visually differentiates assets being used inline vs. as a lead asset/slideshow.

Regarding (3), I'm still in favor of a fallback <img> tag with custom data attributes to flag it as a placeholder. We'll want to customize the WYSIWYG so that image placeholders are displayed in such a way that we make it clear that they're not "normal" content (kind of like the red link styling we do for embed placeholders).

Question on (4): Is the parsing of the article body and rendering of inline assets something you see us handling in the Rails code, or client side?

**Comment by ewr** [comment]
For (4), the answer is yes. :smile: Basically it's the same as the existing assets: the Rails template is where you have the chance to use what you know about the asset to structure the markup most appropriately. Once you're in the JS, you can then do responsive things, etc.

Agree on the display. Like I said, perhaps that's via a flag that gets set on the ContentAsset (via its representation in the UI), which can then be used to color the display, etc.

There are plenty of nifty things you could do to offer shortcuts on the chooser flow (in theory, you could even support dragging an asset right into the body from AssetHost, catching it and handling the plumbing appropriately via JS). Fundamentally, though, the underlying concept is still that you're building one collection of assets attached to the story and then placing them.

**Comment by sdillingham** [comment]
I wonder how the communication between the WYSIWYG editor and the story's ContentAsset objects should work, particularly around setting flags for which assets are being used inline. Use cases I'm thinking about:

1. A user adds an inline asset to the WYSIWYG, then uses the WYSIWYG to remove the inline asset from the body of the story. _What does a good approach look like that enables the WYSIWYG to call back when assets are both added and removed from a story?_
2. A user adds an inline asset to the WYSIWYG. The user then pops up the Asset Chooser, finds the image currently referenced inline and removes it from the collection, and saves the asset collection back to the story. _How do we handle cases like this where an inline asset would get orphaned?

**Comment by ewr** [comment]
You need to be able to parse the body content on WYSIWYG updates and compare what you find against what you were / weren't expecting.

**Comment by sdillingham** [comment]
Makes sense. I suspect we're going to need some more guidance/discussion to arrive at the right approach for this piece.

**Comment by sdillingham** [comment]
Technical flow has been agreed on and implemented by @Ravenstine. Closing.
