### ISSUE TITLE
Product Manager: Survey users and collect e-mails: Get insight and opportunity to follow up

### ISSUE THREAD

**Issue by vsinghkpcc** [SCPR/SCPRv4#315]
As a Product Manager, I want a way to survey users and collect e-mails with minimal UX impact, so that I can gain insight and have the opportunity to follow up for more information, to better inform the ideal web experience for KPCC users.

AC

1) For users who [visits > 2 pages in a session] or [are a returning user and visit > 1 page] (I'm open to suggestions on which one would be better to target - or if anyone has any other suggestions on how to target users for this survey)

2) prompt those users with the question "how likely are you to recommend scpr.org to your friends?" with a 1-10 option (I'm imagining it using similar functionality to the pushdown banner area or breaking news alerts, but far less emphasized so it's generally non-intrusive).

3) If they answer, we then prompt with something like "We're looking for in depth feedback from our users - if you're interested in helping please provide us an e-mail address and we'll follow up with you."

4) Allow the user to dismiss the prompt without answering

5) If the user dismisses the prompt or submits an answer to either question, never show it to them again (as much as we can)

6) Store anonymous answers

7) Store any collected e-mails associated to their answer

**Comment by sdillingham** [comment]
I think the easiest solution to targeting these messages to the appropriate visitor would be to use javascript to set and check for a cookie whose value you might increment either based on visits or pageviews.

@vsinghkpcc: Do you have a preference about where on the page the prompt should be displayed? If it should go at the top of the page, we have the capability via AdHost to run this survey without touching the SCPRv4 codebase. Also: do you have an idea/preference about where you want these answers stored?

**Comment by sdillingham** [comment]
I think the easiest solution to targeting these messages to the appropriate visitor would be to use javascript to set and check for a cookie whose value you might increment either based on visits or pageviews.

@vsinghkpcc: Do you have a preference about where on the page the prompt should be displayed? If it should go at the top of the page, we have the capability via AdHost to run this survey without touching the SCPRv4 codebase. Also: do you have an idea/preference about where you want these answers stored?

**Comment by vsinghkpcc** [comment]
@sdillingham:
 
Yes, top of the page I think would be best.

No strong preference on where the answers should be stored - a google spreadsheet would be ideal - but if it's somewhere I can periodically export a CSV that works, too.

**Comment by sdillingham** [comment]
On second glance, we should actually weight whether this should be delivered via AdHost or inside SCPRv4. Because this is a one-off, transient feature, I tend to want to keep it out of SCPRv4. But given the amount of code we may need to write to get/set cookies, post form data, etc., it may be unwieldy to wedge all that into an AdHost campaign.

**Comment by Ravenstine** [comment]
@sdillingham Would using AdHost mean redirecting the user, displaying an iframe, or still using our own form with AJAX?  I can't seem to find any information on AdHost with Google.  A cookie to track the user seems pretty acceptable, since that can be set on the frontend without having to touch backend code.  If we didn't use something like AdHost, we could still throw up a tiny API on an EC2 instance just to collect survey data, if that's what it takes to not befuddle our SCPRv4 code.

**Comment by vsinghkpcc** [comment]
I think it will be more of transient feature than not, but it would be good to conduct the same experiment again after we were to launch any major design changes to the site - if that better informs a decision.

**Comment by sdillingham** [comment]
Hey @Ravenstine, AdHost is actually our own app that we wrote for delivering custom campaigns (https://github.com/SCPR/AdHost). It was originally written to deliver audio preroll in front of our live stream and podcasts, but @bricker also added the capability for it to deliver custom visual campaigns onto our websites. 

Basically you can create a visual campaign in AdHost with whatever front-end code you want, and SCPRv4 looks for active visual campaigns and delivers them onto the website via AJAX. It's a handy way for us to deliver rich/responsive membership campaigns and surveys onto the website without needing to touch the SCPRv4 code, and also allows us to schedule campaign start and end dates instead of having to add/remove custom campaigns via commits + deploys.   

Relevant code is here:

* https://github.com/SCPR/SCPRv4/blob/00555900e1fda9930c7c6b38d0e15ca2e20f8048/app/assets/javascripts/visual_campaign.js.coffee
* https://github.com/SCPR/SCPRv4/blob/00555900e1fda9930c7c6b38d0e15ca2e20f8048/app/views/shared/new/_document_footer.html.erb#L17-L25
* https://github.com/SCPR/SCPRv4/blob/00555900e1fda9930c7c6b38d0e15ca2e20f8048/app/views/layouts/new/single.html.erb#L8
