### ISSUE TITLE
GA Form Abandonment Tracking Refinement

### ISSUE THREAD

**Issue by vsinghkpcc** [SCPR/SCPRv4#367]
AC

- [x] Investigate and fix the initial setting of the donation type to make sure it comes through on 100% of events we see

**Comment by Ravenstine** [comment]
I did make a few changes to the tracking code.  I currently do not know if they make a difference as I haven't been able to reproduce the problem myself, but the changes I made are in areas where it might make sense for the effects we are seeing to occur.

The staging URL is here:
http://scprcontribute.stage.publicradio.org/contribute.php

When navigating through the form, you can see the history string being generated by executing this in the console:
`window.FormTracker.historyString()`

**Comment by vsinghkpcc** [comment]
Revised AC

- [ ] deploy to production

**Comment by sdillingham** [comment]
As of this morning, I'm seeing far fewer GA events recorded where the only step is "gft": they represent ~5% of all Abandon events since Friday, vs. ~31% of all Abandon events from the same period a week earlier. 

This is significant enough of an improvement that we can consider this resolved  for now.

**Comment by Ravenstine** [comment]
@sdillingham That's good, although it puzzles me how my change *mostly* solved it.
