### ISSUE TITLE
Short List Email Sends Need to be More Resilient

### ISSUE THREAD

**Issue by ewr** [SCPR/SCPRv4#384]
Three times in the last week short list emails have failed to send, twice due to hitting a 500 when POSTing to Eloqua. 

In each case I've manually gone into the console to find the appropriate EloquaEmail object and then manually triggered `async_send_email`.

Our send process needs to automatically retry email sends that fail, particularly for an issue like a 500 on Eloqua's side.

**Comment by Ravenstine** [comment]
I know this is happening with EloquaEmails but, out of curiosity, has it been happening with BreakingNewsAlerts?

**Comment by sdillingham** [comment]
No reports of this happening on the Breaking News Alerts, but obviously it would be smart to set any eloqua send to retry if it fails.

**Comment by sdillingham** [comment]
How much of a delay were you thinking of introducing? I wouldn't wait more than 60 seconds to retry.

**Comment by Ravenstine** [comment]
Yeah, I wasn't thinking much more than that.  I think 60 seconds and 3 total tries makes sense.

**Comment by Ravenstine** [comment]
@sdillingham @ewr 

@ewr and I chatted the other day and landed on the idea of using a job to resend emails, so that's the direction I've now gone in.

So far, I have two versions of changes.  Both are very similar, but there are some differences.  Some peer review would be appreciated.

## Version 1
### Comparison
https://github.com/SCPR/SCPRv4/compare/eloqua_retry_spike3
### Summary
A job called `ResendEmails` Looks for EloquaEmails that have already been attempted to send at least once but failed to send, then tries to resend them by calling `#publish_email`.  Note that I haven't actually scheduled the job to run with Cron because doing so is trivial and I just haven't gotten to it.  I constrained the Job to only act upon EloquaEmails created after 11/17/2015 because I'm paranoid.

## Version 2
### Comparison
https://github.com/SCPR/SCPRv4/compare/eloqua_retry_spike4
### Summary
Almost the same concept as seen in Version 1, but the `EloquaSendable` concern module has been removed and the functionality moved into the `EloquaEmail` model.  Anything that sends an email now does so by creating EloquaEmails, now including `BreakingNewsAlert`.  Emails are no longer queued up with Resque; instead, the `SendEmails` job attempts to send all emails that haven't been sent yet that haven't been attempted more than 3 times.  Test currently fail under this branch(and some need to be moved into eloqua_email_spec), but I'll of course address this.

## Question
Which direction is the better one?  Any thoughts on what improvements can be made?  Is there a 3rd direction I'm haven't considered?

**Comment by ewr** [comment]
I would remove `send_at`. Every extra column is something else that a person coming into the code later needs to spend time learning, so we should only be leaving the things we're actually using.

Conceptually, I like the cleanliness of approach 2 and of having a durable record to reflect the email. 

The one thing that we need to be mindful of in this, though, is the status messaging. If we're switching up how a BreakingNewsAlert works, we just need to make sure a CMS user has the same or better level of visibility after the change than they did before.

If you want to go ahead and open a pull request I have some other code style notes that I can throw in there.

**Comment by sdillingham** [comment]
This was :ship: -ed. Closing.
