### ISSUE TITLE
Need Strategy for Managing Size of Versions Table

### ISSUE THREAD

**Issue by ewr** [SCPR/SCPRv4#414]
The `versions` table is growing unwieldy. For scpr.org, `versions` is now 591K rows and ~2550MB of data and indices.

Questions:
* Should version information be kept forever?
* Is there waste inside the way that version data is currently being stored that could be deleted without shortening the version history?

**Comment by vsinghkpcc** [comment]
AC: Establish one or more strategies for solving this problem.

**Comment by Ravenstine** [comment]
Currently looking into whether or not there's some waste being created in the way we are versioning that can help us reduce the problem.

**Comment by Ravenstine** [comment]
@sdillingham @ewr

I have been taking a look at how we are versioning our content, and I haven't found that much room for improvement in terms of where we can reduce our waste.  We are already saving only changes(i.e. diffs) between versions, so I can only really see considering whether or not there are any fields that we don't want to save.  Whether or not smaller fields are dwarfing fields containing body text is a different question.  The size of our `news_story` table is only 322mb on my machine.

The `versions` table was over 2GB initially on my machine(unfortunately, I didn't record the exact number) but, after enabling compression on the table, I was able to reduce it down to 1063mb, which cut the size nearly in half.  

There is also the option of pruning the table and periodically storing the rest in the cloud(maybe Amazon S3).  Are we still considering something like this as a solution?

Who can I talk to in order to determine how far back we usually need to look at our versions data?  If we never look at anything from over 2 years ago, maybe version data that is over 2 years old can be periodically deleted and we don't need to bother saving any of it.

**Comment by Ravenstine** [comment]
There may be some benefit to not saving versions unless a piece of content has been published.  Right now, we are creating versions even if a news story is in `draft`.

**Comment by sdillingham** [comment]
@Ravenstine I spoke with Eric Zassenhaus and we tentatively agreed on a one-year retention policy, with the idea that we would dump out pruned records to a text file for archival storage. I still need to get buy in from others in the newsroom for 1 year as the right retention timeframe, but for now I think we can march forward with a process that periodically looks for versions more than 1 year old and writes them all to a flat file. Not sure what the best format for that data would be. JSON or CSV?

**Comment by Ravenstine** [comment]
@sdillingham My vote would probably be for CSV since it's more human-eye readable(in this case) and can be easily searched and loaded in Excel without us needing to be there to write an import/view feature for it.  But I'll have to see whether or not that works in reality, since some of those fields can can huge and have a bunch of errors that may need to be escaped for CSV to work.  My second vote would actually go to YAML.

**Comment by Ravenstine** [comment]
So I'm going ahead for now and making a task that will dump versions to CSV and delete ones older than a year, which is easy enough.  Where would we like to save these files?  There's always backing it up to an external service, or maybe we could have it save the CSV in `./tmp`, zip it, and send it to someone via email so that we don't have to worry about working in another service.

**Comment by sdillingham** [comment]
We should to ship this off to disk somewhere, rather than emailing the file. Ideally we're keeping this in a location where other backups live. @ewr, can you suggest a reasonable location?

**Comment by ewr** [comment]
S3.

**Comment by Ravenstine** [comment]
Sigh, I'm getting this:
```ruby
Secretary::Version.find(3309)
#=>Psych::SyntaxError: (<unknown>): found unexpected end of stream while scanning a quoted scalar at line 488 column 5
```

This is happening on production too.  Just thought I'd make a note of it, because it's making my CSV export task a heck of a lot more fun.
