### ISSUE TITLE
Investigate orphaned Immigration stories

### ISSUE THREAD

**Issue by sdillingham** [SCPR/SCPRv4#435]
On the morning of 2/15/16 SCPRv4 started to collect a bunch of errors like this:

https://rpm.newrelic.com/accounts/71496/applications/446356/filterable_errors#/show/5936c7-a1674c98-d404-11e5-9da1-b82a72d22a14/stack_trace?top_facet=transactionUiName&primary_facet=error.class&_k=pb6ow7

Which suggests that there are still some lingering articles in the DB that are tagged as Immigration stories even though that category no longer exists. Would be worth spending the time to cross-reference our current `contentbase_category` records against `content_id`s across all content models, clearing out any `content_id` values that are no longer in use.

**Comment by Ravenstine** [comment]
The following query shows that only the immigration category has a leftover ID in our content rows.
```[NewsStory,ShowSegment,BlogEntry,ContentShell].map{|m| m.joins("LEFT JOIN `contentbase_category` ON `contentbase_category`.`id` = `#{m.table_name}`.`category_id`").where("contentbase_category.id IS NULL").pluck(:category_id) }.flatten.compact.uniq```

It only returns the ID 16 (in production), which is the ID of the deleted immigration category.  Since we're already specifically looking at content with the category 16 when running the migration, I'm not going to include anything to clear out `category_id`s of content with other orphaned categories since there are none.  Hope that makes sense.
