### ISSUE TITLE
Conditionally render CTAs for shows, events

### ISSUE THREAD

**Issue by vsinghkpcc** [SCPR/SCPRv4#492]
AC
- [x] If the story is from a AirTalk, render a commenting CTA that links people to the comment section of that story
- [x] If the story is from any other program, render a subscribe to the podcast CTA that links to the iTunes page
- [x] If the story is promoting an event, render an RSVP CTA that uses the same RSVP url on linked to from that event’s individual page
- [x] Evaluate performance implications and choose the most efficient approach

**Comment by Ravenstine** [comment]
Current changes here, minus the line that could potentially repeat the CTA(which I fixed in a later commit):
https://github.com/SCPR/SCPRv4/commit/00582a50a25d3f35a56235224bb9136b8d427150

As far as performance goes, the initial value is calculated upon article indexing, same as the label.  It would probably be just as fast to evaluate this on rendering with the article object, but that would be less elegant.

**Comment by Ravenstine** [comment]
Call to action flag is generated here:
https://github.com/SCPR/SCPRv4/blob/better_homepage/app/models/homepage_content.rb#L49-L63

Display logic here:
https://github.com/SCPR/SCPRv4/blob/better_homepage/app/views/better_homepage/_call_to_action.html.erb#L1
