### ISSUE TITLE
Track new and unread stories

### ISSUE THREAD

**Issue by vsinghkpcc** [SCPR/SCPRv4#499]
AC: New and unread stories are tracked and displayed as follows: https://kpcc.slack.com/files/katie/F0MREDFPZ/Homepage_Rules__New_Unread_Stories

**Comment by Ravenstine** [comment]
There is a problem viewing the file in the link.  Not sure if it was deleted or if it's a problem with Slack.

**Comment by Ravenstine** [comment]
Comparison of feature branch:
https://github.com/SCPR/SCPRv4/compare/better_homepage...better_homepage_tracking?expand=1

This essentially saves the state of each story that appears on the homepage to localStorage.  This is achieved using pieces extended from Backbone that were developed as part of the Homepage display editing tool in Outpost.  This is because it provides not only a consistent app structure but a consistent localStorage interface, which keeps the door open for things like tracking story attributes on other parts of the site(i.e. we can mark a story as read if they already viewed it through another part of the site).
