### ISSUE TITLE
ensure analytics can track beta vs. regular users

### ISSUE THREAD

**Issue by vsinghkpcc** [SCPR/SCPRv4#506]
AC: We can identify beta usage seperate from homepage usage in our GA from:
- [x] Page views on beta vs. regular can clearly be identified
- [x] Scroll events on beta vs. regular can clearly be identified
- [x] There is a way to track the sitewide behavior for beta users vs. regular users

**Comment by Ravenstine** [comment]
The implementation is there but, since I don't have edit permission, I cannot change the name for **dimension5**.  If @sdillingham could change the name of that dimension to something like "Homepage Type", this ticket could be closed sooner.

**Comment by sdillingham** [comment]
@Ravenstine I've set you up with edit permissions in GA, so you should be unblocked on this ticket now.

**Comment by Ravenstine** [comment]
Just an update on this:

Analytics' live events view doesn't include dimensions for whatever reason.  I've now gotten the chrome extension for analytics to confirm that dimension5 is being set to the homepage type.  It should now be a matter of checking back to GA in a little while to see if events are being successfully mapped to that dimension.  Otherwise, the chrome extension is telling me that everything looks good.

**Comment by Ravenstine** [comment]
**UPDATE**: The "Homepage Type" dimension is successfully coming in for "Homepage" events.  Though I'm not seeing it there for scroll events, even though it should be there.  This may be due to not having scroll tracking added to the beta homepage, so I'm going to have to either add scroll tracking or try it out on the old homepage and see what happens in the next day(it takes a long time for the full events to finally show up in GA).

**Comment by Ravenstine** [comment]
![image](https://cloud.githubusercontent.com/assets/5193330/15901369/ddb94f48-2d57-11e6-9e9b-35eeabaac9ea.png)
This is an example of what you'd get by filtering by Dimension5/HomepageType.
