### ISSUE TITLE
Hidden Gems on the Homepage

### ISSUE THREAD

**Issue by vsinghkpcc** [SCPR/SCPRv4#528]
AC
- [x] There is a way to manage hidden gems in a way that provides a consumable source
- [x] There is a way display hidden gems on the homepage given a consistent source
- [x] Every time a user visits the homepage we display a random hidden gem

**Comment by Ravenstine** [comment]
Hidden gems can now be added by dropping a partial into `views/better_homepage/hidden_gems`.  I felt like this was the best approach for beta and, if we needed one to show up elsewhere besides the footer, the `hidden_gem` helper can be used.  Since the concept of a "hidden gem" might change, I am going to leave it this way for now.
