### ISSUE TITLE
What's Next Improvements: Documentation

### ISSUE THREAD

**Issue by vsinghkpcc** [SCPR/SCPRv4#544]
AC: We have a clear list of improvements / updates we'd like to make to the What's Next TOC
- [x] The animation of headlines as they disappear
- [x] Dealing with what happens to the TOC when it hits "obstacles" on the page
- [x] Responsiveness solution

**Comment by tinykb** [comment]
Headlines as they disappear (generally): https://www.dropbox.com/s/w6zddt83iw84brm/WhatsNext-READARTICLE.mp4?dl=0

Headlines as they disappear (detail): https://www.dropbox.com/s/pghr0aukzpxgh16/WhatsNext-READARTICLEdetail.mp4?dl=0

What happens when WN runs into a big photo: https://www.dropbox.com/s/9m9g2l4x5tqsyqr/WhatsNext-BIGPHOTO.mp4?dl=0

**Comment by tinykb** [comment]
As for the responsive issue, I think the entire feature goes away on smaller screens. Folks on tablet/mobile expect to scroll. (And we don't have an empty gray bar to fill 😹 )

**Comment by tinykb** [comment]
Issue moved to [SCPR/design #137](https://github.com/SCPR/design/issues/137) via [**ZenHub**](https://www.zenhub.com/)
