### ISSUE TITLE
New Homepage view needs to implement fragment caching

### ISSUE THREAD

**Issue by sdillingham** [SCPR/SCPRv4#550]
Currently the new homepage is querying and building all dynamic contents on every page request. That won't scale once the beta is public and needs to handle meaningful traffic.

AC: 

- [ ] Investigate and propose at least one solution for how we can improve the performance of loading related content.
- [ ] Implement fragment caching on Check it Out ~~and main homepage story contents~~ that expires whenever the current homepage model is saved or a new homepage is published.
- [ ] Implement fragment caching on the broadcast bar to expire when the current show changes (similar to https://github.com/SCPR/SCPRv4/blob/master/app/views/layouts/homepage.html.erb#L16)

**Comment by Ravenstine** [comment]
@sdillingham How concerned are we about reflecting changes in stories(e.g. headline, typo correction in summary, etc.) after a beta homepage has been published?  I ask this because fragment caching the page in a way that significantly reduces computation also means that something has to be done to expire a fragment cache on update, unless we aren't concerned about that.  Or maybe the fragment cache can just expire periodically?  Adding code to 'touch' the homepage on update isn't exactly difficult, but I want to avoid too much coupling.

Also, are you thinking that caching will benefit us in terms of the amount of work that Rails would be doing or the work that Elasticsearch would be doing?  Elasticsearch seems very performant, but I've never had to scale with it so IDK.

**Comment by sdillingham** [comment]
All good questions @Ravenstine. Let's rethink the AC for this ticket, and base any work instead on what we're able to see in New Relic. We'll be rolling out the new homepage gradually which gives us the opportunity to observe, learn and iterate on performance as we go.

https://rpm.newrelic.com/accounts/71496/applications/446356/transactions#id=5b22436f6e74726f6c6c65722f6265747465725f686f6d65706167652f696e646578222c22225d

Looking at the transaction graph for the new homepage, it actually looks like the biggest opportunity to improve performance is in the shared/_extra.html.erb partial. I suspect that calling `recent_related_content` on each News article is where we're taking a performance hit. 

Let's re-scope the AC for this ticket to simply investigate and propose at least one solution for how we can improve the performance of loading related content. Sound good?

**Comment by sdillingham** [comment]
Actually, I still think there's a clear win if we cache the current program being displayed in the broadcast bar. I'd like to keep that AC in place.

**Comment by Ravenstine** [comment]
👍

**Comment by Ravenstine** [comment]
It will probably be worth it to fragment cache on a per-story basis, if it turns out there aren't any other good ways to get better performance out of related content.  Since the page itself already seems to have decent performance, the biggest win would could be to cache the stories individually and that would mean that their changes would be reflected immediately since they'd get re-indexed.

**Comment by Ravenstine** [comment]
Well, here's what I've found so far.

Normally, on my machine, I get around 200ms without caching.  Just fragment caching each of the story elements, I get it down to around 150ms.  If I cache the entire page, it comes down as low as 60ms.  Not sure why the improvement over the last step is so significant; could come down to the amount of Ruby execution.  This does include static assets that are served in my development environment which, when disabled, knocks off a few dozen milliseconds.

I'd like to keep things simple, so I am thinking along these lines:
- BetterHomepage expires its fragment cache when updated.
- HomepageContent touches BetterHomepage when updated.
- Fragment Cache expires periodically(e.g. 5 minutes).

The trade-off I see to this strategy is that related content for each of the stories won't always be *exactly* newer than 48 hours, but newer than that give or take the cache expiry period.  That doesn't sound so bad to me.  Depending on how up-to-date the content must be on the homepage, eliminating the second option might not be so bad.

Note that this just addresses caching the content and not the Check It Out or anything else.

Will continue thinking about this.

**Comment by Ravenstine** [comment]
One of the reasons for the current speed is that I had originally planned for each request to only require 2 ES queries.  That is, until we had the requirement for related content to have thumbnails; and, since it seemed like we wanted our content to immediately reflect changes, I decided to query the articles for each of the related contents.  I avoided storing the thumbnail with the related content in the index because I felt like data was starting to get too duplicative but, if we do that, we wouldn't have to do so many queries anymore.  I think that now that I have looked at fragment caching, I should now look at how things can be improved without the cache.

**Comment by sdillingham** [comment]
Agreed!

**Comment by sdillingham** [comment]
@vsinghkpcc @Ravenstine I'm not sure we achieved the first AC on this ticket (improve the performance of loading 1recent_related_content). Should we reopen? Looking at the NR transactions performance graph, I think there's still an opportunity to improve.

**Comment by Ravenstine** [comment]
@sdillingham Yes, I'll re-open it.  Though, I am puzzled that I'm not seeing as much of a corresponding performance gain as I did locally.  While I think the caching itself is still an improvement, I'm going to try a different strategy.

**Comment by Ravenstine** [comment]
I feel like the AC has been met, as the performance is now much better in Production.

To summarize, I ended up abandoning the effort to rely on an Elasticsearch index to retrieve the homepage contents.  It ended up being more performant to precache the beta homepage using the same mechanism that we are using to precache the classic homepage.  Edits to the homepage and its contents should also show up much more quickly now.
