### ISSUE TITLE
Implement homepage timestamp

### ISSUE THREAD

**Issue by Ravenstine** [SCPR/SCPRv4#563]
See https://github.com/SCPR/design/issues/122.

- [x] We stop displaying the timestamp when older than an hour
- [x] Use the "time ago" format (ex "34 minutes ago")

**Comment by sdillingham** [comment]
A requirement for this will need to be to conditionally hide the timestamp when the homepage hasn't been updated in over `N` hours. So if the homepage was last updated more than 1 hour ago, we might not want to promote that information to our audience since that would imply that the homepage is stale.
