### ISSUE TITLE
Double articles being pulled into remote articles

### ISSUE THREAD

**Issue by ezass** [SCPR/SCPRv4#612]
Looks like we're getting double posts from NPR. FYI. 
![screen shot 2016-08-12 at 11 00 58 am](https://cloud.githubusercontent.com/assets/994636/17632389/ed79d9f4-607c-11e6-898e-87815344e110.png)

**Comment by Ravenstine** [comment]
@ezass I am pretty confident this has been fixed since I have merged a change into production, and no new duplicates occur no matter how many times I press the sync button.  Ping me if the problem recurs.

**Comment by Ravenstine** [comment]
Nevermind, the problem seems to have recurred.  I may have to prevent duplicates at the database level or something along those lines.  It all seemed to be working as expected yesterday.

**Comment by Ravenstine** [comment]
Perhaps it's related to a race condition:
https://stackoverflow.com/questions/26500908/concurrent-cause-duplicate-records-inserted

Just a guess, since we seem to run into this problem on occasion in completely different parts of the code without good or any reasons for why it would happen at the application level.

**Comment by Ravenstine** [comment]
Ok, we are definitely no longer seeing duplicates.  Remote articles now have uniqueness set to true on one of its indexes.  I'd still like to figure out where there are two competing processes trying to download remote articles, but I'd eat my hat if the database level constraint doesn't work.
