### ISSUE TITLE
Why this story didn't show up in Remote Articles

### ISSUE THREAD

**Issue by frankreporting** [SCPR/SCPRv4#621]
A story on Six Flags Magic Mountain that was local and probably of interest to our audience slipped through the cracks. Likely has to do with how it was tagged so we'd just like to figure out what happened and determine if there is another tag we should add to what we're currently pulling for Remote Articles. [The story is here](http://www.npr.org/sections/alltechconsidered/2016/08/22/490895637/on-six-flags-virtual-reality-coaster-the-ride-is-just-half-the-thrill).

**Comment by sdillingham** [comment]
So it looks like this wasn't available for import because we're not currently importing content from the All Tech Considered blog (it's NPR API ID is `102920358`).

I've addressed this in https://github.com/SCPR/SCPRv4/commit/bf4eef408d84797da9050faa3b49c9e92ff3414c which will be deployed in a few minutes.
