### ISSUE TITLE
Site Unification: Generalizing homepage layout

### ISSUE THREAD

**Issue by vsinghkpcc** [SCPR/SCPRv4#704]
AC
- [x] Repurpose new homepage layout for internal pages

**Comment by Ravenstine** [comment]
Basically done, though won't be released into production until it becomes a part of the other unification tickets, but here's a codepen that demos it.

https://codepen.io/Ravenstine/pen/woNWry?editors=1100

The cool thing is that it solves a few problems with the last implementation, and appears to work on most browsers without any JavaScript. (the current implementation requires a tiny bit of it to fix some bugs on non-chrome browsers)

**Comment by nakedsushi** [comment]
I think I broke it by adding some content to some of the left divs. That left div gets pushed all the way down in desktop mode.
https://codepen.io/anon/pen/ObqmzJ?editors=1100

**Comment by Ravenstine** [comment]
@nakedsushi Yeah, that's fine.  Those sections are absolute-positioned.  The CSS that I added to make them flow beneath each other assumes that they are all the same size.  Weird shit happens when one is of a larger size.  If they are a different size, it's implied that custom CSS gets added to adjust.  For most of what we are doing, we will probably only need a single left-aside.

**Comment by Ravenstine** [comment]
See here:
https://codepen.io/Ravenstine/pen/xRBrVB?editors=1100

Though, note that the left asides don't expand the container.  Not really a problem, though, as we'd expect the center column to be longest 99.9% of the time.

**Comment by nakedsushi** [comment]
Got it. As long as the code is self-explanatory (maybe we can name that ‘left’ class ‘something-fixed-height’), LGTM. I just don’t want another dev (like me) to come to it months later to make a change to the left and wonder why it barfs when adding a new element or something.
