### ISSUE TITLE
Adjust Pushdown Styles

### ISSUE THREAD

**Issue by vsinghkpcc** [SCPR/SCPRv4#756]
AC

- [ ] Allow for more specific control over individual pushdown styles that are consistent across all pages of scpr.org (i.e. the pushdown height and fonts should be able to be adjusted from the pushdown itself, yet display consistently on both the homepage and article pages)

**Comment by Ravenstine** [comment]
The style sheet coming from our campaign system is using a CSS class(`.call-to-action`), which conflicts with an identical class name used on the homepage.  The better solution is to adjust the style sheet that comes with the campaign pushdown to use a different class name with its own margin/padding properties which would display uniformly.  There's nothing preventing the incoming style sheet from producing uniform styles, especially since it comes in after the application style has been loaded.

**Comment by Ravenstine** [comment]
The next time this issue comes up, I can help adjust the style sheet being used in our campaign system.  That's the right place make the adjustment.
