### ISSUE TITLE
Segment pages not displaying related content

### ISSUE THREAD

**Issue by vsinghkpcc** [SCPR/SCPRv4#856]
AC
- [ ] segment pages display related content (example: http://www.scpr.org/programs/airtalk/2017/05/08/56628/president-trump-looks-to-fill-federal-court-seats/)

**Comment by arellaTV** [comment]
The `related content` section's last appearance (that I could find) was sometime in June of last year: https://web.archive.org/web/20160613113910/http://www.scpr.org/programs/airtalk/2016/06/10/49613/a-clinton-warren-ticket-potential-dream-pairing-or/
Captured pages after that show it missing. A quick look is showing that the `Article` model doesn't have anything showing up in its `related_content` and `links` properties.

I'll go ahead and use the above page as a point of reference for how it should be and report back here if I've found a reasonable solution!

**Comment by arellaTV** [comment]
- The `content` object being fed into `/views/shared/cwidgets/_related_links.html.erb` was resolving with empty array values for `content.links` and `content.related_content`
- I changed the way we access these properties in the view so that we're passing in `article` now instead of `article.get_article`. I also removed the `links.present?` check since Rails was telling me that there was no `links` property.
- The change should only affect the `segment` view specifically.

**Comment by arellaTV** [comment]
- **Staging:**
http://scprv4-staging.scprdev.org/programs/airtalk/2016/06/10/49613/a-clinton-warren-ticket-potential-dream-pairing-or/
- **Web Archive:** https://web.archive.org/web/20160613113910/http://www.scpr.org/programs/airtalk/2016/06/10/49613/a-clinton-warren-ticket-potential-dream-pairing-or/

Staging now has the related links section.

**Comment by arellaTV** [comment]
Shipped to production and behaves as expected! :shipit:
